# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildCode
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run test
    displayName: 'test'
    continueOnError: 'true'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
    displayName: Publish Code Coverage
  
  - task: PublishTestResults@2
    displayName: 'Publish Jest Unit Test Results'
    inputs:
      testResultsFiles: 'junit.xml'
      mergeTestResults: 'true'
      failTaskOnFailedTests: 'true'

  - script: |
      npm run build
    displayName: 'build'

- job: PrintSomething
  steps:
  - script: |
      echo "Hello World"
    displayName: Print